#!/bin/sh /etc/rc.common

# Copyright 2020 Google LLC.
# Copyright (C) 2021 CZ.NIC z.s.p.o. (https://www.nic.cz/)
# SPDX-License-Identifier: Apache-2.0

USE_PROCD=1
START=99

export TS_NO_LOGS_NO_SUPPORT=true

start_service() {
  local state_file
  local port
  local std_err std_out
  local http_proxy https_proxy no_proxy
  local always_use_derp

  config_load tailscale
  config_get_bool std_out "settings" log_stdout 1
  config_get_bool std_err "settings" log_stderr 1
  config_get port "settings" port 41641
  config_get state_file "settings" state_file /etc/tailscale/tailscaled.state
  config_get fw_mode "settings" fw_mode nftables
  config_get http_proxy "settings" http_proxy
  config_get https_proxy "settings" https_proxy
  config_get no_proxy "settings" no_proxy
  config_get_bool always_use_derp "settings" always_use_derp 0

  /usr/sbin/tailscaled --cleanup

  procd_open_instance
  procd_set_param command /usr/sbin/tailscaled

  # Starting with v1.48.1 ENV variable is required to enable use of iptables / nftables.
  # Use nftables by default - can be changed to 'iptables' in tailscale config.
  procd_set_param env TS_DEBUG_FIREWALL_MODE="$fw_mode"

  # Disable logging to log.tailscale.com.
  procd_append_param env TS_NO_LOGS_NO_SUPPORT=true

  [ -z "$http_proxy" ] || {
    procd_append_param env HTTP_PROXY="$http_proxy"
    procd_append_param env http_proxy="$http_proxy"
  }
  [ -z "$https_proxy" ] || {
    procd_append_param env HTTPS_PROXY="$https_proxy"
    procd_append_param env https_proxy="$https_proxy"
  }
  [ -z "$no_proxy" ] || {
    procd_append_param env NO_PROXY="$no_proxy"
    procd_append_param env no_proxy="$no_proxy"
  }
  [ "$always_use_derp" -eq 0 ] ||
    procd_append_param env TS_DEBUG_ALWAYS_USE_DERP=true

  # Set the port to listen on for incoming VPN packets.
  procd_append_param command --port "$port"
  procd_append_param command --state "$state_file"

  procd_set_param respawn
  procd_set_param stdout "$std_out"
  procd_set_param stderr "$std_err"

  procd_close_instance
}

stop_service() {
  /usr/sbin/tailscaled --cleanup
}
