#!/bin/sh /etc/rc.common

START=98
STOP=09
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /root/bin/voidboost-egress-watchdog.sh
    procd_set_param respawn 5 10 0
    procd_set_param stdout 0
    procd_set_param stderr 1
    procd_close_instance
}
